State: 9
Info: ''
Logo: pack://application:,,,/Plain Craft Launcher 2;component/Images/Blocks/Fabric.png
ReleaseTime: 2025-10-07 17:17
VersionFabric: 0.19.2
VersionLegacyFabric: ''
VersionQuilt: ''
VersionLabyMod: ''
VersionOptiFine: ''
VersionLiteLoader: false
VersionForge: ''
VersionNeoForge: ''
VersionCleanroom: ''
VersionApiCode: 1902
VersionOriginal: 1.21.10
VersionOriginalMain: 21
VersionOriginalSub: 10
VersionArgumentIndieV2: true
VersionLaunchCount: 1
VersionVanillaName: 1.21.10
VersionVanilla: 21.0.10
