VersionFabric:0.19.2
VersionAdvanceJvm:
State:9
VersionVanillaName:1.21.10
VersionArgumentIndieV2:True
VersionVanilla:21.0.10
Info:正式版 1.21.10, Fabric 0.19.2
IsStar:False
VersionLiteLoader:False
Logo:pack://application:,,,/Plain Craft Launcher 2;component/Images/Blocks/Fabric.png
ReleaseTime:2025-10-07 17:17
